### PR TITLE
Updates to the latest versions

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
waiting on a release

**Comment by hyleung** [comment]
@adriancole I can do a release, then merge this - thanks for updating this repo!

**Comment by hyleung** [comment]
I went ahead an published 2.3.1, but the snapshot version should be ok ( can always bump this one in a subsequent commit).

**Comment by codefromthecrypt** [comment]
Thanks tons

On 24 Feb 2018 12:13 pm, "Ho Yan Leung" <notifications@github.com> wrote:

I went ahead an published 2.3.1, but the snapshot version should be ok (
can always bump this one in a subsequent commit).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hyleung/ratpack-zipkin-example/pull/3#issuecomment-368198274>,
or mute the thread

**Pull request merged**
